name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      matrix:
        go-version:
        - 1.x
        - 1.17.x
        os:
        - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
      with:
        go-version: 1.x
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
      with:
        version: v1.46.2