name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      matrix:
        go-version:
        - 1.x
        - 1.17.x
        os:
        - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923
      with:
        go-version: 1.x
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
      with:
        version: v1.46.2